name: Make build
on: workflow_dispatch
env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Poetry and dependencies
      run: ./scripts/poetry-install.sh
    - name: Make build
      run: $POETRY build
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist