name: Test Coverage
on: 
  pull_request:
    branches:
      main
  push:
    branches:
        "main"
  workflow_dispatch:
env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
  HPCC_USERNAME: ${{ secrets.HPCC_USERNAME }}
  HPCC_PASSWORD: ${{ secrets.HPCC_PASSWORD }}
  DUMMY_USERNAME: ${{ vars.DUMMY_USERNAME }}
  DUMMY_PASSWORD: ${{ vars.DUMMY_PASSWORD }}
  HPCC_HOST: ${{ vars.HPCC_HOST }}
  HPCC_PORT: ${{ vars.HPCC_PORT }}
  DUMMY_HOST: ${{ vars.DUMMY_HOST }}
  DUMMY_PORT: ${{ vars.DUMMY_PORT }}
  LANDING_ZONE_IP: ${{ vars.LANDING_ZONE_IP }}
  LANDING_ZONE_PATH: ${{ vars.LANDING_ZONE_PATH }}
  DFU_CLUSTER: ${{ vars.DFU_CLUSTER }}
  ENV: ${{ vars.ENV }}
  HPCC_PROTOCOL: ${{ vars.HPCC_PROTOCOL }}
jobs:
  coverage:
    name: PyTest coverage
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry and dependencies
        run: ./scripts/poetry-install.sh
      - name: Run Tests
        run: |
          $POETRY run coverage run
        continue-on-error: true
      - name: Get Cover 
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
            # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
            name: python-coverage-comment-action
            # If you use a different name, update COMMENT_FILENAME accordingly
            path: python-coverage-comment-action.txt