name: poetry
on: [push, workflow_dispatch]
env: 
  POETRY_HOME: /opt/poetry
jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.2.0
    - name: Build Artifact
      run: $POETRY_HOME/bin/poetry build