name: poetry-install
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    # # - name: Install Poetry and dependencies
    # #   run: ./scripts/poetry-install.sh
    # - name: Build Artifact
    #   run: $POETRY build
    # - name: Lint with ruff
    #   uses: chartboost/ruff-action@v1
    #   continue-on-error: true
