name: Test Coverage
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
  workflow_dispatch:
env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
jobs:
  coverage:
    name: PyTest coverage
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry and dependencies
        run: ./scripts/poetry-install.sh
      - name: Run Tests
        run: |
          $POETRY run coverage run -m pytest
        continue-on-error: true
      - name: Run Coverage
        run: $POETRY run coverage xml
      - name: Get Cover 
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
