name: release
on:
  release:
    types: [published]


env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
jobs:
  build:
    name: Make Release build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Poetry and dependencies
      run: ./scripts/poetry-install.sh
    - name: Make build
      run: $POETRY build
    - uses: actions/upload-artifact@v4
      with:
        name: distfiles
        path: dist/
        if-no-files-found: error

  upload-github:
    name: Upload (GitHub)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: dist/

      - run: gh release upload ${{ github.event.release.tag_name }} dist/*.{tar.gz,whl}
        env:
          GH_TOKEN: ${{ github.token }}
  
  ## Future integration with PyPI
  # upload-pypi:
  #   name: Upload (PyPI)
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/project/pyhpcc/
  #   permissions:
  #     id-token: write
  #   needs: build
  #   steps:
  #     - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
  #       with:
  #         name: distfiles
  #         path: dist/

  #     - uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
  #       with:
  #         password: <SECRET PYPI TOKEN>