name: Ruff
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
