name: Run tests
on: 
  push:
    branches:
      main
  pull_request:
    branches:
      main
env: 
  POETRY_HOME: ${{vars.POETRY_HOME}}
  POETRY: ${{vars.POETRY}}
  HPCC_USERNAME: ${{ secrets.HPCC_USERNAME }}
  HPCC_PASSWORD: ${{ secrets.HPCC_PASSWORD }}
  DUMMY_USERNAME: ${{ vars.DUMMY_USERNAME }}
  DUMMY_PASSWORD: ${{ vars.DUMMY_PASSWORD }}
  HPCC_HOST: ${{ vars.HPCC_HOST }}
  HPCC_PORT: ${{ vars.HPCC_PORT }}
  DUMMY_HOST: ${{ vars.DUMMY_HOST }}
  DUMMY_PORT: ${{ vars.DUMMY_PORT }}
  LANDING_ZONE_IP: ${{ vars.LANDING_ZONE_IP }}
  LANDING_ZONE_PATH: ${{ vars.LANDING_ZONE_PATH }}
  DFU_CLUSTER: ${{ vars.DFU_CLUSTER }}
  ENV: ${{ vars.ENV }}
  HPCC_PROTOCOL: ${{ vars.HPCC_PROTOCOL }}

jobs:
  tests:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Poetry and dependencies
      run: ./scripts/poetry-install.sh
    - name: Python tests
      run: $POETRY run pytest -rs